baseurl: ""
url: "https://daszeal.github.io"
title: "Peter Jiang"
permalink: /:year/:month/:day/:title/

collections:
  posts:
    output: true

  tools:
    output: true
    permalink: /tools/:name/

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
